manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/glove0x0a-png
    - name: caksoylar
      url-base: https://github.com/caksoylar
    # START #####
    - name: badjeff
      url-base: https://github.com/badjeff
    # END #######

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml

    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main

   # START #####
    - name: zmk-analog-input-driver
      remote: badjeff
      revision: main
    # END #######

  self:
    path: config
